server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice_db
    username: postgres
    password: ajaz@amu786
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    prefer-ip-address: true


  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


